version: '2'
services:
  hyper-hdr:
    container_name: hyperhdr
    hostname: hyperhdr
    image: ggamboa/hyperhdr:latest
    network_mode: host
    devices:
      - /dev/video0:/dev/video0
    environment:
      - TZ=Europe/Madrid
      - PGID=1000
      - PUID=1000

    volumes:
      - /home/pi/containersdata/hyperhdr:/config
    restart: unless-stopped
